### ISSUE TITLE
Numpy style docstrings

### ISSUE THREAD

**Issue by TejasAvinashShetty** [goerz/cookiecutter-pypackage#10]
Can we use numpy style docstrings ?
For example  https://github.com/numpy/numpydoc/blob/master/doc/example.py

If not, can we configure this cookiecutter or modify it in some way  to use numpy style docstrings.

**Comment by goerz** [comment]
No, I don't like Numpy style docstrings

**Comment by goerz** [comment]
(feel free to fork and modify according to your taste)

**Comment by TejasAvinashShetty** [comment]
Thank you for your prompt reply Dr @goerz .

**Comment by TejasAvinashShetty** [comment]
Could you please guide me as to how to go about it?

**Comment by goerz** [comment]
Sorry, no, you're on your own with this one
